USE Inventario
GO

CREATE TABLE TArticulos (
	AId INT PRIMARY KEY IDENTITY(1,1),
	ANombre VARCHAR(20) NOT NULL,
	ADescripcion VARCHAR(50) NOT NULL,
	ACantidad INT NOT NULL,
	ACreatedBy INT NOT NULL,
	AValor MONEY NOT NULL,
	APId INT NOT NULL
)
GO


CREATE TABLE TProveedores(
	ProvId INT PRIMARY KEY IDENTITY(1,1),
	ProvName VARCHAR(30) NOT NULL,
	ProvIni DATETIME NULL,
	ProvFin DATETIME NULL
)
GO


CREATE TABLE TUsuario(
	UserId INT PRIMARY KEY IDENTITY(1,1),
	UHPass VARBINARY(MAX),
	UPrivId INT DEFAULT 1 NOT NULL,
	UCreated DATETIME NOT NULL,
	ULastLogin DATETIME NOT NULL,
	UStatus BIT NOT NULL
)
GO


CREATE TABLE TPerfiles(
	PerId INT PRIMARY KEY IDENTITY(1,1),
	PNombre VARCHAR(25),
	PPermisos VARCHAR(MAX)
)
GO


CREATE TABLE TAcciones(
	AccId INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
	ANombre VARCHAR(30) NOT NULL
)
GO


CREATE TABLE TRegistros(
	RId INT PRIMARY KEY IDENTITY(1,1),
	RFecha DATETIME NOT NULL,
	RAccionId INT NOT NULL,
	RModifiedBy INT NOT NULL
)
GO


CREATE TABLE TBorrados(
	BId INT PRIMARY KEY IDENTITY(1,1),
	BANombre VARCHAR(20) NOT NULL,
	BADescripcion VARCHAR(50) NOT NULL,
	BCantidad INT NOT NULL,
	BDeletedBy INT NOT NULL,
	BFecha DATETIME NOT NULL
)
GO


------------------------------------------------------------   LLAVES FORÁNEAS

-- ARTICULOS
ALTER TABLE TArticulos
ADD CONSTRAINT FK_ACREATEDBY
	FOREIGN KEY (ACreatedBy)
	REFERENCES TUsuario (UserId);
GO

ALTER TABLE TArticulos
ADD CONSTRAINT FK_APROVID
	FOREIGN KEY (APId)
	REFERENCES TProveedores (ProvId);
GO

-- USUARIOS
ALTER TABLE TUsuario
ADD CONSTRAINT FK_UPERFIL
	FOREIGN KEY(UPrivId)
	REFERENCES TPerfiles (PerId);
GO

-- REGISTROS
ALTER TABLE TRegistros
ADD CONSTRAINT FK_RACCION
	FOREIGN KEY(RAccionId)
	REFERENCES TAcciones (AccId);
GO

ALTER TABLE TRegistros
ADD CONSTRAINT FK_RMODIFIEDBY
	FOREIGN KEY(RModifiedBy)
	REFERENCES TUsuario (UserId);
GO

-- BORRADOS
ALTER TABLE TBorrados
ADD CONSTRAINT FK_DELETEDBY
	FOREIGN KEY (BDeletedBy)
	REFERENCES TUsuario  (UserId);
GO